# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  npm-qlik:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: svc-pipeline-2
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - npm-qlik
    schedule:
      interval: "daily"
      time: "22:26"
      timezone: "UTC"
    groups:
      minor-patch:
        update-types:
        - "minor"
        - "patch"
