name: 1_workflow level environment variables
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev
env:
    var1: Hello From workflow Level 1
    var2: Hello From workflow Level 2

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Display wf_level_env_var using shell-style variable expansion
        run: |
          echo "wf env var1: $var1"
          echo "wf env var2: $var2"

      - name: Display wf_level_env_var using GH actions expression syntax
        run: |
          echo "wf env var1: ${{ env.var1 }}"
          echo "wf env var2: ${{ env.var2 }}"
     
      - name: using if statement
        if: ${{ always() && env.var1 == 'Hello From workflow Level 2' }}
        run: |
          echo "The result of 2 * 3 is:" $((2 * 3))
  