# Can be overridden at job level and step level
# Is available in all jobs and their steps unless overridden


name: 1_workflow level environment variables
on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - dev
  #   branches-ignore:
  #     - dev
env:
    var1: Hello From workflow Level 1
    var2: Hello From workflow Level 2

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: step1, Display workflow environment variable using shell-style variable expansion
        run: |
          echo "workflow env var1: $var1"

      - name: step2, Display workflow environment variable using GH actions expression syntax
        run: |
          echo workflow env var2: ${{ env.var2 }}
     
      - name: step3, using if statement
        if: ${{ always() && env.var1 == 'Hello From workflow Level 1' }}
        run: |
          echo The result of 2 * 3 is: $((2 * 3))

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: step1, 
        run: |
          echo workflow env var1: $var1
          echo workflow env var2: ${{ env.var2 }}
  