# Only applies to that step
# Cannot be overridden (because it only exists for that step)

name: 3_step level environment variables
on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - dev1
  #   branches-ignore:
  #     - dev1

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Shell Variable Expansion $var1, GH Actions Expression Syntax using $ {{}}
        env: # only accessed in this step (can be placed also after run but not before name:)
            var1: Hello From step Level 1
            var2: Hello From step Level 2
        run: |
          echo step level env var1: $var1
          echo step level env var2: ${{ env.var2 }}

     
     