name: test environment variables
on:
  push:
    branches: 
      dev
  workflow_dispatch:
env:
  var1: myworkflowvar1
  var2: myworkflowvar2
  var3: myworkflowvar3

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Display wf env var using Shell Variable Expansion
        run: |
          echo "wf env var1: $var1"
          echo "wf env var2: $var2"
          echo "wf env var3: $var3"

      - name: Display wf env var using GH actions expression syntax
        run: |
          echo "wf env var1: ${{ env.var1 }}"
          echo "wf env var2: ${{ env.var2 }}"
          echo "wf env var3: ${{ env.var3 }}"
     
      - name: using if statement
        if: ${{ always() || env.var1 == 'myworkflowvar2' }}
        run: |
          echo "The result of 2 * 3 is:" $((2 * 3))
  