# Only applies to that step
# Cannot be overridden (because it only exists for that step)

name: 3_step level environment variables
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

env:
  var1: Hello From workflow-Level 1
  var2: Hello From workflow-Level 2

jobs:



  job1:
    runs-on: ubuntu-latest

    env:
      var1: Hello From Job-Level 1
      var2: Hello From Job-Level 2

    steps:
      - name: Display step level environment variable (using Shell Variable Expansion)
        env:
            var1: Hello From step-Level 1
            var2: Hello From step-Level 2
        run: |
          echo step level environment variable 1: $var1
          echo step level environment variable 2: ${{ env.var2 }}

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: step1, 
        run: |
          echo workflow env var1: $var1
          echo workflow env var2: ${{ env.var2 }}

     
     