# Only applies to that step
# Cannot be overridden (because it only exists for that step)

name: 4_All level environment variables
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

env:
  var1: Hello From workflow-Level 1
  var2: Hello From workflow-Level 2

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.status.outputs.job1_status }}
    env:
      var1: Hello From Job1-Level 1
      var2: Hello From Job1-Level 2

    steps:
      - name: using Shell Variable Expansion
        id: status
        env:
            var1: Hello From step-Level 1
            var2: Hello From step-Level 2
        run: |
          echo $var1
          echo ${{ env.var1 }}
          echo "job1_status=${{ env.var1 }}" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.status.outputs.job2_status }}
    env:
      var1: Hello From Job2-Level 1
      var2: Hello From Job2-Level 2

    steps:
      - name: using Shell Variable Expansion
        id: status
        run: |
          echo $var1
          echo ${{ env.var2 }}
          echo "job2_status=${{ env.var2 }}" >> $GITHUB_OUTPUT
  
  notify:
    needs: [job1, job2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Slack

        # run: |
        #   payload=$(cat <<eof
        #   {
        #     "text": "🔔 Workflow completed1.
        #   📦😊Job1 result: ${{ needs.job1.outputs.result }}
        #   📦👌Job2 result: ${{ needs.job2.outputs.result }}"          
        #   }
        #   eof)
        #   curl -X POST -H 'Content-type: application/json' \
        #   --data "$payload" \
        #   ${{ secrets.ASF_SLACK_WEBHOOK_URL }}



        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "attachments": [
              {
                "color": "#36a64f",
                "text":"🟢 _*Workflow completed*_\nJob1 result: ${{ needs.job1.outputs.result }}\nJob2 result: ${{ needs.job2.outputs.result }}"
              }
            ]
          }' \
          ${{ secrets.ASF_SLACK_WEBHOOK_URL }}





     
     