# Only applies to that step
# Cannot be overridden (because it only exists for that step)

name: 4_All level environment variables
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

env:
  var1: Hello From workflow-Level 1
  var2: Hello From workflow-Level 2

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.status.outputs.job_status }}
    env:
      var1: Hello From Job1-Level 1
      var2: Hello From Job1-Level 2

    steps:
      - name: using Shell Variable Expansion
        id: status
        env:
            var1: Hello From step-Level 1
            var2: Hello From step-Level 2
        run: |
          echo $var1
          echo ${{ env.var2 }}
          echo "job_status=${{ env.var2 }}" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    env:
      var1: Hello From Job2-Level 1
      var2: Hello From Job2-Level 2

    steps:
      - name: step1, 
        run: |
          echo $var1
          echo ${{ env.var2 }}
  
  notify:
    needs: [job1, job2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Slack
        run: |
          run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🔔 Workflow completed.\nJob1 result: ${{ needs.job1.outputs.result }}"}' \
          ${{ secrets.ASF_SLACK_WEBHOOK_URL }}



     
     