name: a1_reusable_wf
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      finalSum:
        description: The sum from job1
        value: "First value: ${{ jobs.job1.outputs.calculateSum1 }} /
                Second value: ${{ jobs.job1.outputs.calculateSum2 }}"
      
      finalDivision: 
        description: The division from job1
        value: "First value: ${{ jobs.job1.outputs.calculateDivision1 }} /
                Second value: ${{ jobs.job1.outputs.calculateDivision2 }}"
      
      finalMulti:
        description: The multiplication from job2
        value: ${{ jobs.job2.outputs.calculateMulti }}
      
      finalSubtraction:
        description: The subtraction from job2
        value: ${{ jobs.job2.outputs.calculateSubtraction }}
  push:
    branches:
      - dev1
      



jobs:

  job1:
    name: hello job1
    runs-on: ubuntu-latest
    outputs:
      calculateSum1: ${{ steps.sum.outputs.sumResult1 }}
      calculateSum2: ${{ steps.sum.outputs.sumResult2 }}
      calculateDivision1: ${{ steps.divide.outputs.divisionResult1 }}
      calculateDivision2: ${{ steps.divide.outputs.divisionResult2 }}

    steps:
      - name: Write sum result to output
        id: sum
        run: |
          echo "sumResult1=$((15 + 35))" >> $GITHUB_OUTPUT
          echo "sumResult2=$((120 + 35))" >> $GITHUB_OUTPUT

      - name: Write division result to output
        id: divide
        run: |
          echo "divisionResult1=$((100 / 4))" >> $GITHUB_OUTPUT
          echo "divisionResult2=$((100 / 10))" >> $GITHUB_OUTPUT



  job2:
    name: hello job2
    runs-on: ubuntu-latest
    outputs:
      calculateMulti: " First value: ${{ steps.multi.outputs.multiResult1 }} /
                        Second value: ${{ steps.multi.outputs.multiResult2 }}"
      calculateSubtraction: " First value: ${{ steps.subtract.outputs.subtractResult1 }} /
                              Second value: ${{ steps.subtract.outputs.subtractResult1 }}"
    needs: job1

    steps:
      - name: Write multiplication result to output
        id: multi
        run: |
          echo "multiResult1=$((4 * 6))" >> $GITHUB_OUTPUT
          echo "multiResult2=$((4 * 6))" >> $GITHUB_OUTPUT

      - name: Write subtraction result to output
        id: subtract
        run: |
          echo "subtractResult1=$((27 - 7))" >> $GITHUB_OUTPUT
          echo "subtractResult2=$((27 - 7))" >> $GITHUB_OUTPUT
      
      - name: step1, print job1 output
        run: |
          echo print sumResult and divisionResult from job1:
          echo ${{ needs.job1.outputs.calculateSum1 }}
          echo ${{ needs.job1.outputs.calculateSum2 }}
          echo ${{ needs.job1.outputs.calculateDivision1 }}
          echo ${{ needs.job1.outputs.calculateDivision2 }}

          echo print multiplyResult and subtractResult from job2:
          echo ${{ steps.multi.outputs.multiResult1 }}
          echo ${{ steps.multi.outputs.multiResult2 }}
          echo ${{ steps.subtract.outputs.subtractResult1 }}
          echo ${{ steps.subtract.outputs.subtractResult2 }}