name: a1_reusable_wf
on:
  workflow_dispatch:
  push:
    branches:
      - dev1
  workflow_call:
    inputs:
      exampleInput:
        description: A secret the caller must provide
        required: true
        type: string
        
    secrets:
      MY_SECRET:
        description: A secret the caller must provide
        required: true
  
    outputs:
      finalSum:
        description: The sum from job1
        value: First value ${{ jobs.write_to_output.outputs.sum }}
      
      finalDivision: 
        description: The subtraction from job1
        value: First value ${{ jobs.write_to_output.outputs.subtraction }}
      
      finalMulti:
        description: The multiplication from job2
        value: First value ${{ jobs.write_to_output.outputs.multiplication }}
      
      finalSubtraction:
        description: The division from job2
        value: First value ${{ jobs.write_to_output.outputs.division }}

    # outputs:
    #   all_results:
    #     description: The results from job1
    #     value: > 
    #       sum: ${{ jobs.write_to_output.outputs.sum }}
    #       subtraction: ${{ jobs.write_to_output.outputs.subtraction }}
    #       multiplication: ${{ jobs.write_to_output.outputs.multiplication }}
    #       division: ${{ jobs.write_to_output.outputs.division }}
      
      
          
          

jobs:

  write_to_output:
    name: write arithmetic operations to output
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.sum.outputs.sum }}
      subtraction: ${{ steps.subtract.outputs.subtraction }}
      multiplication: ${{ steps.multi.outputs.multiplication }}
      division: ${{ steps.divide.outputs.division }}

    steps:
      - name: Write sum result to output
        id: sum
        run: echo sum=$((50 + 10)) >> $GITHUB_OUTPUT

      - name: Write subtraction result to output
        id: subtract
        run: echo subtraction=$((80 - 10)) >> $GITHUB_OUTPUT

      - name: Write multiplication result to output
        id: multi
        run: echo multiplication=$((8 * 10)) >> $GITHUB_OUTPUT
        
      - name: Write division result to output
        id: divide
        run: echo division=$((180 / 2)) >> $GITHUB_OUTPUT
      
      - name: Read sum result from output
        run: |
          echo job1 sum result: ${{ steps.sum.outputs.sum }}
          echo job1 subtraction result: ${{ steps.subtract.outputs.subtraction }}
          echo job1 multiplication result: ${{ steps.multi.outputs.multiplication }}
          echo job1 division result: ${{ steps.divide.outputs.division }}

  read_from_output:
    name: Read the result from arithmetic operations
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.operations.outputs.sum }}
      subtraction: ${{ steps.operations.outputs.subtraction }}
      multiplication: ${{ steps.operations.outputs.multiplication }}
      division: ${{ steps.operations.outputs.division }}
    needs: write_to_output

    steps:
      - name: Write some arithmetic operations to output
        id: operations
        run: |
          echo sum=$((10 + 10)) >> $GITHUB_OUTPUT
          echo subtraction=$((40 - 10)) >> $GITHUB_OUTPUT
          echo multiplication=$((4 * 10)) >> $GITHUB_OUTPUT
          echo division=$((100 / 2)) >> $GITHUB_OUTPUT


      - name: Print job2 output
        run: |
          echo job2: sum result: ${{ steps.operations.outputs.sum }}
          echo job2: subtraction result:  ${{ steps.operations.outputs.subtraction }}
          echo job2: multiplication result:  ${{ steps.operations.outputs.multiplication }}
          echo job2: division result:  ${{ steps.operations.outputs.division }}

      - name: Print job1 output
        run: |
          echo job1: sum result: ${{ needs.write_to_output.outputs.sum }}
          echo job1: division result: ${{ needs.write_to_output.outputs.division }}
          echo job1: multiplication result: ${{ needs.write_to_output.outputs.multiplication }}
          echo job1: subtraction result: ${{ needs.write_to_output.outputs.subtraction }}


