name: a1_reusable_wf
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      finalSum:
        description: "The sum from job1"
        value: ${{ jobs.job1.outputs.calculateSum }}
      
      finalMulti: 
        description: "The product from job2" 
        value: ${{ jobs.job2.outputs.calculateMulti }}


       

jobs:

  job1:
    name: hello job1
    runs-on: ubuntu-latest
    outputs:
      calculateSum: ${{ steps.calc.outputs.sumResult }}
    steps:
      - id: calc
        name: step1 in job1
        run: echo "sumResult=$((15 + 35))" >> $GITHUB_OUTPUT


  job2:
    name: hello job2
    runs-on: ubuntu-latest
    outputs:
      calculateMulti: ${{ steps.multiplication.outputs.multiResult }}
    needs: job1

    steps:
      - name: step1, print job1 output
        run: echo print calculateSum from job1 ${{ needs.job1.outputs.calculateSum }}

      - name: step2, write to output
        id: multiplication
        run: echo "multiResult=$((4 * 6))" >> $GITHUB_OUTPUT