name: a1_reusable_wf_tbd
on:
  workflow_call:
    inputs:
      exampleInputNew:
        description: "default value"
        required: true
        type: string

    secrets:
      asf_secret:
        description: A secret that caller must provide
        required: false

jobs:
  job1_write_to_output:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret
        id: use_secret
        run: |
          echo Example input from workflow_call is: ${{ inputs.exampleInputNew }}