name: a1_reusable_wf_tbd
on:
  push:
    branches:
      - dev1
  workflow_dispatch:
  workflow_call:
    inputs:
      exampleInputNew:
        description: "default value"
        required: true
        type: string

    secrets:
      asf_secret:
        description: A secret that caller must provide
        required: false

jobs:
  print_values_from_caller_wf:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret
        id: use_secret
        run: |
          echo input value from workflow_call is: ${{ inputs.exampleInputNew }}
          echo secret value from workflow_call is: ${{ secrets.asf_secret }}

  write_to_and_read_from_output:
    name: this is a good name
    runs-on: ubuntu-latest
    outputs:
      sumOfNumber: ${{ steps.sum.outputs.summation }}
      subtractionOfNumber: ${{ steps.sum.outputs.subtraction }}
      multiplicationOfNumber: ${{ steps.sum.outputs.multiplication }}
      divisionOfNumber: ${{ steps.sum.outputs.division }}

    steps:
      - name: Write sum result to output
        id: sum
        run: |
          echo summation=$(( 5 + 5)) >> $GITHUB_OUTPUT
          echo subtraction=$(( 30 - 10)) >> $GITHUB_OUTPUT
          echo multiplication=$(( 2 * 15)) >> $GITHUB_OUTPUT
          echo division=$(( 80 / 2)) >> $GITHUB_OUTPUT

      - name: read sum result from output
        run: |
          echo summation is: ${{ steps.sum.outputs.summation }}
          echo subtraction is: ${{ steps.sum.outputs.subtraction }}
          echo multiplication is: ${{ steps.sum.outputs.multiplication }}
          echo division is: ${{ steps.sum.outputs.division }}

