name: a1_reusable_wf_tbd
on:
  push:
    branches:
      - dev1
  workflow_dispatch:
  workflow_call:
    inputs:
      exampleInputNew:
        description: "default value"
        required: true
        type: string

    secrets:
      asf_secret:
        description: A secret that caller must provide
        required: false

jobs:
  print_values_from_caller_wf:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret
        id: use_secret
        run: |
          echo input value from workflow_call is: ${{inputs.exampleInputNew}}
          echo secret value from workflow_call is: ${{secrets.asf_secret}}

  write_read_same_job:
    name:  write_to_and_read_from_output
    runs-on: ubuntu-latest
    outputs:
      sum: ${{steps.math.outputs.summation}}
      sub: ${{steps.math.outputs.subtraction}}
      multi: ${{steps.math.outputs.multiplication}}
      div: ${{steps.math.outputs.division}}

    steps:
      - name: write to output
        id: math
        run: |
          echo summation=$(( 5 + 5)) >> $GITHUB_OUTPUT
          echo subtraction=$(( 30 - 10)) >> $GITHUB_OUTPUT
          echo multiplication=$(( 2 * 15)) >> $GITHUB_OUTPUT
          echo division=$(( 80 / 2)) >> $GITHUB_OUTPUT

      - name: read from step in same job
        run: |
          echo sum in same job is: ${{steps.math.outputs.summation}}
          echo sub in same job is: ${{steps.math.outputs.subtraction}}
          echo multi in same job is: ${{steps.math.outputs.multiplication}}
          echo div in same job is: ${{steps.math.outputs.division}}
  
  read_from_other_job:
    runs-on: ubuntu-latest
    needs:  write_read_same_job

    steps:
      - name: read from step in other job
        run: |
          echo sum in other job is: ${{needs.write_read_same_job.outputs.sum}}
          echo sub in other job is: ${{needs.write_read_same_job.outputs.sub}}
          echo multi in other job is: ${{needs.write_read_same_job.outputs.multi}}
          echo div in other job is: ${{needs.write_read_same_job.outputs.div}}


