name: Basic Workflow
on:
  workflow_dispatch:
    inputs:
      my_car_info:
        description: "info about my car"
        required: false
        default: "red"
        type: string
      email:
        description: "User email"
        required: false
        type: string
      name:
        description: "Person to greet"
        default: "World"
        required: true
        type: string
      city:
        description: "Favorite city"
        required: true
        default: "Tupelo"
        type: choice
        options:
          - New York
          - Seattle
          - Tupelo
      fav-color-blue:
        description: "Is your favorite color blue"
        required: true
        type: boolean
jobs:
  greet:
    name: "Greetings, Program!"
    runs-on:
      - ubuntu-latest
    steps:
      - name:
        run: |
          echo "Hello ${{ github.event.inputs.name }}"
          echo "Your favorite city is ${{ github.event.inputs.city }}"
          echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue }}"