name: Basic Workflow_new3
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "World"
        required: true
        type: string
      city:
        description: "Favorite city"
        default: "Tupelo"
        required: true
        type: choice
        options:
          - New York
          - Seattle
          - Tupelo
      fav-color-blue:
        description: "Is your favorite color blue"
        required: true
        type: boolean
jobs:
  greet:
    name: "Greetings, Program"
    runs-on:
      - ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name || 'World' }}"
          echo "Your favorite city is ${{ github.event.inputs.city || 'Tupelo'}}"
          echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue || 'true' }}"
  
  
