name: Basic Workflow
on:
  push:
    branches: dev
  workflow_dispatch:
    inputs:
      base_url:
        type: choice
        description: "Base URL for the system tests"
        required: true
        default: "https://system-test-soak.us.qlik-stage.com"
        options:
          - "https://system-test-peach.us.qlik-stage.com"
          - "https://system-test-soak.us.qlik-stage.com"
          - "https://system-test-wario.us.qlik-stage.com"
          - "https://sta-byok.us.qlik-stage.com"
      my_car_info:
        description: info about my car
        required: false
        default: volvo
        type: string
      email:
        description: "User email"
        required: false
        type: string
      name:
        description: "Person to greet"
        default: "World"
        required: true
        type: string
      city:
        description: "Favorite city"
        required: true
        default: "Tupelo"
        type: choice
        options:
          - New York
          - Seattle
          - Tupelo
      fav-color-blue:
        description: "Is your favorite color blue"
        required: false
        type: boolean
jobs:
  greet:
    name: "Greetings, Program!"
    runs-on:
      - ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "Your base url is: ${{ github.event.inputs.base_url }}"
          echo "you like ${{ github.event.inputs.my_car_info }} car"
          echo "and your email is ${{ github.event.inputs.email }}"
          echo "and you want to greet ${{ github.event.inputs.name }} person"
          echo "Your favorite city is ${{ github.event.inputs.city }}"
          echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue }}"