name: test environment variables
on:
  push:
    branches: 
      dev
  workflow_dispatch:
env:
  var1: myworkflowvar1
  var2: myworkflowvar2
  var3: myworkflowvar3

jobs:
  display-env:
    runs-on: ubuntu-latest

    steps:
      - name: Display workflow-env var
        run: |
          echo "wf env var1: $var1"
          echo "wf env var2: $var2"
          echo "wf env var3: $var3"