name: test GITHUB_OUTPUT/GITHUB_ENV
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
    # branches-ignore:
    #   - dev

jobs:

  job1:
    name: hello job 1
    runs-on: ubuntu-latest
    # this is to be used in other jobs and not same job (job1)
    outputs:
      output1: ${{ steps.id1.outputs.my_output1 }}
      output2: ${{ steps.id2.outputs.my_output2 }}

    steps:    
      # to be used in same job (job1) 
      - name: writing value to GITHUB_ENV
        run: |
          echo "my_GITHUB_ENV=This is written to GITHUB_ENV" >> $GITHUB_ENV

      - name: reading content of GITHUB_ENV in 2 ways in same job
        run: |
          echo "step1 output:" $my_GITHUB_ENV
          echo "step1 output: ${{ env.my_GITHUB_ENV }}"

      - name: writing value to GITHUB_OUTPUT to use in same job
        id: kianosh
        run: |
          echo "my_output1_in_job1=content of GITHUB_OUTPUT used in same job" >> $GITHUB_OUTPUT
        
      - name: reading a value from GITHUB_OUTPUT
        run: |
          echo "here is the content of GITHUB_OUTPUT:" ${{ steps.kianosh.outputs.my_output1_in_job1 }}
  

      # to be used in other jobs
      - name: wwriting a value to GITHUB_OUTPUT using my_output1
        id: id1
        run: |
          echo "my_output1=This is" >> $GITHUB_OUTPUT

      - name: writing a value to GITHUB_OUTPUT using my_output2
        id: id2
        run: |
          echo "my_output2=Ardevan" >> $GITHUB_OUTPUT
# *****************************************************************************************
  job2:
    name: hello job 2
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.id1.outputs.my_output1 }}
      output2: ${{ steps.id2.outputs.my_output2 }}

    steps:
      - name: writing a value to GITHUB_OUTPUT using my_output1
        id: id1
        run: |
          echo "my_output1=learning" >> $GITHUB_OUTPUT

      - name: writing a value to GITHUB_OUTPUT using my_output2
        id: id2
        run: |
          echo "my_output2=how writing to and" >> $GITHUB_OUTPUT
# *****************************************************************************************  
  # job3:
  #   name: hello job 3
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.id1.outputs.my_output1 }}
  #     output2: ${{ steps.id2.outputs.my_output2 }}

  #   steps:
  #     - name: writing a value to GITHUB_OUTPUT using my_output1
  #       id: id1
  #       run: |
  #         echo "my_output1=reading from" >> $GITHUB_OUTPUT    

  #     - name: writing a value to GITHUB_OUTPUT using my_output2
  #       id: id2
  #       run: |
  #         echo "my_output2=to GITHUB_OUTPUT works" >> $GITHUB_OUTPUT
  # *****************************************************************************************
  # job4:
  #   name: hello job 4
  #   runs-on: ubuntu-latest
  #   needs: [job1, job2, job3]
  #   steps:
  #     - name: reading contents of GITHUB_OUTPUT from job 1,2 and 3
  #       run: |
  #         echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }} 
  #         echo ${{ needs.job2.outputs.output1 }} ${{ needs.job2.outputs.output2 }} 
  #         echo ${{ needs.job3.outputs.output1 }} ${{ needs.job3.outputs.output2 }}