name: test GITHUB_OUTPUT
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

jobs:

  job1:
    name: hello job 1
    runs-on: ubuntu-latest
  
    steps:    
   
      - name: step1, writing a value to GITHUB_OUTPUT
        id: step1_id
        run: echo my_GITHUB_OUTPUT1=$((2 *3)) >> $GITHUB_OUTPUT

      - name: step2, writing a value to GITHUB_OUTPUT
        id: step2_id
        run: |
          echo my_GITHUB_OUTPUT2=bbbbbbbbbbbbbbbbbbbbbbb >> $GITHUB_OUTPUT
          echo my_GITHUB_OUTPUT3=ccccccccccccccccccccccc >> $GITHUB_OUTPUT

      - name: step6, reading a value from GITHUB_OUTPUT
        run: |
          echo step4 output: ${{ steps.step1_id.outputs.my_GITHUB_OUTPUT1 }}
          echo step2 output: ${{ steps.step2_id.outputs.my_GITHUB_OUTPUT2 }}
          echo step2 output: ${{ steps.step2_id.outputs.my_GITHUB_OUTPUT3 }}


  # *****************************************************************************************
  job2:
    needs: job1
    name: hello job 2
    runs-on: ubuntu-latest

    steps:
      - name: step1, use the sum result from job1
        run: |
          echo The sum result from job 1: ${{ needs.job1.outputs.my_GITHUB_OUTPUT1 }}
          echo The sum result from job 1: ${{ needs.job1.outputs.my_GITHUB_OUTPUT2 }}
          echo The sum result from job 1: ${{ needs.job1.outputs.my_GITHUB_OUTPUT3 }}

    
   