name: test GITHUB_OUTPUT/GITHUB_ENV
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    name: hello job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.my_output1 }}
      output2: ${{ steps.step3.outputs.my_output2 }}
    

    steps:
      - name: my step1 name
        id: step1
        run: |
          echo "my_GITHUB_OUTPUT=This is written to GITHUB_OUTPUT" >> $GITHUB_OUTPUT
          echo "my_GITHUB_ENV=This is written to GITHUB_ENV" >> $GITHUB_ENV
          echo "my_output1=This is written to output1" >> $GITHUB_OUTPUT


      - name: my step2 name
        id: step2
        run: |
          echo "step1 output:" ${{ steps.step1.outputs.my_GITHUB_OUTPUT }}
          echo "step1 output:" $my_GITHUB_ENV
          echo "step1 output:" ${{ env.my_GITHUB_ENV }}
      
      - name: my step3 name
        id: step3
        run: |
          echo "my_output2=This is written to output2" >> $GITHUB_OUTPUT

  job2:
    name: hello job 2
    runs-on: ubuntu-latest
    steps:
      - name: print out output2 from job1 step3
        run: |
          echo "this is output from job1 step3" ${{ steps.step1.outputs.output1 }}
          echo "this is output from job1 step3" ${{ steps.step3.outputs.output2 }}

   



         

      
  
 

   

    