name: test GITHUB_OUTPUT/GITHUB_ENV
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    name: hello job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.ID3.outputs.my_output1 }}
      output2: ${{ steps.ID1.outputs.my_output2 }}
      output3: ${{ steps.ID1.outputs.my_output3 }}

    steps:      
      - name: my step1 name
        id: ID3
        run: |
          echo "my_output1=Hello" >> $GITHUB_OUTPUT

  job2:
    name: hello job 2
    runs-on: ubuntu-latest
    steps:
      - name: print out output2 from job1 step3
        id: ID1
        run: |
          echo "my_output2=world" >> $GITHUB_OUTPUT

  job3:
    name: hello job 3
    runs-on: ubuntu-latest
    steps:
      - name: print out output2 from job1 step3
        id: ID1
        run: |
          echo "my_output3=from GH outputs" >> $GITHUB_OUTPUT    

  job4:
    name: hello job 4
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: print out output2 from job1 step3
        id: ID1
        run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job2.outputs.output2 }} ${{ needs.job3.outputs.output3 }}