name: test GITHUB_OUTPUT
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

jobs:

  job1:
    name: hello job 1
    runs-on: ubuntu-latest
  
    steps:    
   
      - name: step1, writing a value to GITHUB_OUTPUT
        id: step1_id
        run: echo resultOfSum=$((2 + 3)) >> $GITHUB_OUTPUT

      - name: step2, writing a value to GITHUB_OUTPUT
        id: step2_id
        run: |
          echo resultOfMulti=$((25 * 25)) >> $GITHUB_OUTPUT
          echo my_string=ccccccccccccccccccccccc >> $GITHUB_OUTPUT

      - name: step3, reading a value from GITHUB_OUTPUT
        run: |
          echo step1 output: ${{ steps.step1_id.outputs.resultOfSum }}
          echo step2 output: ${{ steps.step2_id.outputs.resultOfMulti }}
          echo step2 output: ${{ steps.step2_id.outputs.my_string }}
   