name: test GITHUB_OUTPUT using outputs
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  #   branches-ignore:
  #     - dev

jobs:

  job1:
    name: hello job 1
    runs-on: ubuntu-latest

    outputs:
      calculateSum: ${{ steps.step1_id.outputs.sumResult }}
      calculateMulti: ${{ steps.step2_id.outputs.multiResult }}
  
    steps:    

      - name: step1, to be passed to another jobs
        id: step1_id
        run: echo sumResult=$((10 + 10)) >> $GITHUB_OUTPUT
    
      - name: step2, to be passed to another jobs
        id: step2_id
        run: echo multiResult=$((10 * 10)) >> $GITHUB_OUTPUT


  job2:
    name: hello job 2
    runs-on: ubuntu-latest
    needs: [job1]

    steps:
      - name: step1, use output from job 1
        run: |
          echo step1 output: ${{ needs.job1.outputs.calculateSum }}
          echo step1 output: ${{ needs.job1.outputs.calculateMulti }}







   