name: Print GitHub Ref

on:
  push:
    branches:
      - dev
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref
        run: echo "The github.ref is:" ${{ github.ref }}