name: Go Through System Test Workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev

jobs:
  print-github-context:
    runs-on: ubuntu-latest
    steps:

      - name: print branch info
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "Static string for comparison: refs/heads/qlikreleaser"
      
      
      
