name: Go Through System Test Workflow

on:
  push:
    branches:
      - dev
jobs:
  github_ref:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref
        run: echo "The github.ref is:" ${{ github.ref }}

      - name: Print github.run_id
        run: echo "The github.run_id is:" ${{ github.run_id  }}