name: Hello world workflow
on:
  push:
    branches:
      - ardfar68_branch
  pull_request:
    branches:
      - ardfar68_branch
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world 2"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world 3"
        shell: bash