name: test step outputs

on: 
  push

jobs:
  output-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a step output
        id: step1
        run: echo "MY_OUTPUT=Hello from step 1" >> $GITHUB_ENV

      - name: Use the step output
        run: | 
          echo Alt 1_Step 1 said : $MY_OUTPUT