# echo "${{ toJSON(github) }}" > github_context.json
# echo github_context.json

name: test step outputs

on: 
  push

jobs:
  output-job:
    runs-on: ubuntu-latest
    steps:
      - name: Declare GITHUB_ENV and GITHUB_OUTPUT
        id: step1
        run: |
          echo my_github_env=Hello GH env from step 1 >> $GITHUB_ENV
          echo my_github_output=Hello GH output from step 1 >> $GITHUB_OUTPUT


      - name: DecPrint GITHUB_ENV and GITHUB_OUTPUT
        run: | 
          echo "1: the content of environment var:" $my_github_env
          echo "2: the content of output file:" ${{ steps.step1.outputs.my_github_output }}

      - name: Github context object
        run: |
          echo "3: the content of gh context object:" ${{ toJSON(github) }}
          

