# echo "${{ toJSON(github) }}" > github_context.json
# echo github_context.json
# echo "3: the content of gh context object: ${{ toJSON(github) }}"

name: test step outputs

on: 
  push

env:
  env_var_at_wf_level_1: ${{ toJSON(github) }}
  env_var_at_wf_level_2: "this is another variable at wf level"

jobs:
  output-job:
    runs-on: ubuntu-latest
    steps:
      - name: Declare GITHUB_ENV and GITHUB_OUTPUT
        id: step1
        run: |
          echo my_github_env=Hello GH env from step 1 >> $GITHUB_ENV
          echo my_github_output=Hello GH output from step 1 >> $GITHUB_OUTPUT


      - name: DecPrint GITHUB_ENV and GITHUB_OUTPUT
        run: | 
          echo "1: the content of environment var:" $my_github_env
          echo "2: the content of output file:" ${{ steps.step1.outputs.my_github_output }}

      - name: store context object
        run: |
          echo "${{ toJSON(github) }}" > github_context.json
          
      - name: print context object
        run: |
          echo "Contents of github_context.json:"
          cat github_context.json

      - name: print env variable declared at wf-level
        run: | 
          echo "first run: $env_var_at_wf_level_1"
          echo "second run: $env_var_at_wf_level_2"
        env:
          env_var_at_step_level_1: "${{ toJSON(github) }}"
          env_var_at_step_level_2: "this is another variable at step level"

      - name: print env variable declared at step-level
        run: |
          echo "$env_var_at_step_level_1"
          echo "$env_var_at_step_level_2"




