name: Linting-python-code

on: push

jobs:
  python-linting-code:
   runs-on: ubuntu-latest

   steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Super-Linter
      uses: super-linter/super-linter@v4.9.4
            
    
  
