name: Linting-python-code

on: push

jobs:
  python-linting-code:
   runs-on: ubuntu-latest

   steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Super-Linter
      uses: super-linter/super-linter@v7.2.1
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}