name: Slack notification wf
on:
  push:
    branches: 
      - dev
    # branches-ignore:
    #   - dev
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      var1: jobLevelVar1
      var2: jobLevelVar2
      SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Send Slack notification
        id: step1
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🎉 Deployment successful!"}' "$SLACK_URL"