name: test GITHUB_OUTPUT
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo "hello world"
      

   
 

   

    