name: test GITHUB_OUTPUT
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    name: hello job 1
    runs-on: ubuntu-latest

    steps:
      - name: my step1 name
        id: step1
        run: |
          echo "my_GITHUB_OUTPUT=This is written to GITHUB_OUTPUT" >> $GITHUB_OUTPUT
          echo "my_GITHUB_ENV=This is written to GITHUB_ENV" >> $GITHUB_ENV

      - name: access step 1 output
        id: step2
        run: |
          echo "step1 output:" ${{ steps.step1.outputs.my_GITHUB_OUTPUT }}
          echo "step1 output:" $my_GITHUB_ENV
          echo "step1 output:" ${{ env.my_GITHUB_ENV }}

  job2:
    name: hello job 2
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: access output from job 1
        id: step1
        run: |
          echo "step1 output:" ${{ needs.job1.outputs.my_GITHUB_OUTPUT }}
         

      
  
 

   

    