name: workflow for run test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Run test.js
       # run: node ../src/test.js
        run: |
          echo "Listing root directory"
          ls -l  # Check the contents of the root folder
          echo "Listing src directory"
          ls -l src  # Check the contents of src folder
          node src/test.js  # Run the test directly from the src folder
