name: test GITHUB_OUTPUT
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    name: hello job 1
    runs-on: ubuntu-latest

    steps:
      - name: my step1 name
        id: step1
        run: echo "my_output=hello step1" >> $GITHUB_ENV
        # run: echo "my_output=hello step1" >> $GITHUB_ENV

      - name: access step 1 output
        id: step2
        run: echo "step1 output:" ${{ steps.step1.outputs.my_output }}
      
  
 

   

    