name: test GITHUB_OUTPUT
on:
  push:
    branches: 
      - dev
  workflow_dispatch:


jobs:
  job1:
    name: hello job 1
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello step1"

      - run: echo "hello step2"
      
  job2:
    name: hello job 2
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo "hello step1"

      - name: step2
        run: echo "hello step2"
   
 

   

    