name: Variables and Context
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

env:
  VAR1: myworkflowvar1
  VAR2: myworkflowvar2
  VAR3: myworkflowvar3

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        env:
          #GITHUB_CONTEXT: ${{ toJSON(github) }}
          GITHUB_CONTEXT: ${{ toJSON(github.sha) }}

        run: |
          echo "asf1:  $GITHUB_CONTEXT"
          echo "asf2:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          echo "asf3:  ${{ github.event.inputs.name }}"
          echo "asf4:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"         
           
