name: Variables and Context
on: 
  workflow_dispatch: 
    inputs:
      name:
        description: Person to greet
        default: World
        required: true

env:
  VAR1: myworkflowvar1
  VAR2: myworkflowvar2
  VAR3: myworkflowvar3

jobs:
  

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1: Dump GitHub context"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        # All below 3 variants works fine
        run: echo "GITHUB_CONTEXT"
        # run: echo %GITHUB_CONTEXT%
        # run: echo env.GITHUB_CONTEXT
      - name: "Step 2: Print input name"
        run: |
          echo "Input name in the wf is: ${{ github.event.inputs.name }}"
          echo "Repo full name is: ${{ github.event.repository.full_name }}"
          echo "Repo branch url is: ${{ github.event.repository.branches_url }}"
          echo "Repo created date is: ${{ github.event.repository.created_at }}"
          echo "Repo name is: ${{ github.event.repository.name }}"
        
  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: $ {{ steps.step1.outputs.step1value }}
      output2: $ {{ steps.step1.outputs.step2value }}

    steps:
      - name: Step 1
        id: step1
        run: echo "step1value=hello" >> $GITHUB_OUTPUT
      - name: Step 2
        id: step2
        run: echo "step2value=world" >> $GITHUB_OUTPUT
  
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: print out from job 2
        run: echo ${{ needs.job2.outputs.output1 }} ${{ needs.job2.outputs.output2 }}